on:
  push:
    branches:
      - main

name: 🚀 Despliegue Laravel API a Producción

jobs:
  web-deploy:
    name: 🎉 Despliegue API
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el código
      - name: 🚚 Obtener código más reciente
        uses: actions/checkout@v4

      # 2. Configurar PHP y Composer
      - name: ⚙️ Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, intl, bcmath, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300
          coverage: none

      # 3. Instalar dependencias de Laravel
      - name: 📦 Instalar dependencias con Composer
        run: composer install --no-dev --optimize-autoloader

      # 7. Optimizar configuración (sin cache de vistas o rutas innecesarias)
      - name: ⚡ Optimizar configuración
        run: php artisan config:cache

      # 8. Subir archivos al servidor vía FTP (ignorando .env y directorios innecesarios)
      - name: 📂 Subir archivos al servidor FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: dev.imaarica.cl
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./
          server-dir: ./intranet/
          exclude: |
            **/.git*
            **/node_modules/**
            **/.env*
            **/storage/**
            **/tests/**
            **/docker-compose.yml
            **/package-lock.json

      # 6. Subir la carpeta 'public' a 'public_html/intranet'
      - name: 📂 Subir carpeta 'public' a 'public_html/intranet'
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: dev.imaarica.cl
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./public/
          server-dir: ./public_html/intranet/
          exclude: |
            **/.git*
            **/node_modules/**
            **/.env*
            **/tests/**

    # 9. 📢 Nota Importante sobre el Servidor
    # ---------------------------------------------------------------
    # ⚠️ Después del despliegue, asegúrate de:
    #
    # ✅ Tener un archivo `.env` correctamente configurado en el servidor.
    # ✅ Ejecutar manualmente en el servidor:
    #      - composer install --no-dev --optimize-autoloader
    #      - php artisan migrate --force (si no se migró correctamente)
    #      - php artisan config:cache
    # ✅ Configurar permisos correctos en las carpetas:
    #      - storage/
    #      - bootstrap/cache
    # ✅ Reiniciar el servicio PHP-FPM o el servidor web si es necesario.
    # ---------------------------------------------------------------
