on:
  push:
    branches:
      - main

name: 🚀 Despliegue Laravel a Producción

jobs:
  web-deploy:
    name: 🎉 Despliegue
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el código
    - name: 🚚 Obtener código más reciente
      uses: actions/checkout@v4

    # 2. Configurar PHP y Composer
    - name: ⚙️ Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, intl, bcmath, gd, pdo, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300
        coverage: none

    # 3. Instalar dependencias de Laravel
    - name: 📦 Instalar dependencias con Composer
      run: composer install --no-dev --optimize-autoloader

    # 4. Crear archivo .env temporal para key:generate
    - name: 📄 Crear archivo .env temporal
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=https://localhost" >> .env

    # 5. Generar clave de la aplicación
    - name: 🔑 Generar clave de la aplicación
      run: php artisan key:generate

    # 6. Ejecutar migraciones
    #- name: 🗂️ Ejecutar migraciones
    #  run: php artisan migrate --force

    # 7. Optimizar caché de Laravel
    - name: ⚡ Optimizar caché de Laravel
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    # 8. Subir archivos al servidor vía FTP (ignorando .env)
    - name: 📂 Subir archivos al servidor FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: dev.imaarica.cl
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./
        server-dir: ./
        exclude: |
          **/.git*
          **/node_modules/**
          **/vendor/**
          **/.env*
          **/storage/**
          **/tests/**
          **/docker-compose.yml
          **/package-lock.json
